using System.Collections;
using UnityEngine;
using UnityEditor;
using SplineMesh;

public class Growing_Root : MonoBehaviour
{
    private GameObject generated;
    private Spline spline;
    private MeshBender meshBender;

    public Mesh mesh;
    public Material material;
    public Vector3 rotation;
    public Vector3 scale;

    public float startScale = 1;

    private void OnValidate()
    {
        Init();
    }

    void Start()
    {

    }

    void Update()
    {

    }

    private void Contort()
    {
        float nodeDistance = 0;
        int i = 0;
        foreach (var n in spline.nodes)
        {
            float nodeDistanceRate = nodeDistance / spline.Length;
            float nodeScale = startScale * nodeDistanceRate;
            n.Scale = new Vector2(nodeScale, nodeScale);
            if (i < spline.curves.Count)
            {
                nodeDistance += spline.curves[i++].Length;
            }
        }

        if (generated != null)
        {
            meshBender.SetInterval(spline, 0, spline.Length);
            meshBender.ComputeIfNeeded();
        }
    }

    private void Init()
    {
        string generatedName = "generated by " + GetType().Name;
        var generatedTranform = transform.Find(generatedName);
        generated = generatedTranform != null ? generatedTranform.gameObject : UOUtility.Create(generatedName, gameObject,
            typeof(MeshFilter),
            typeof(MeshRenderer),
            typeof(MeshBender));

        generated.GetComponent<MeshRenderer>().material = material;

        meshBender = generated.GetComponent<MeshBender>();
        spline = GetComponent<Spline>();

        meshBender.Source = SourceMesh.Build(mesh)
            .Rotate(Quaternion.Euler(rotation))
            .Scale(scale);
        meshBender.Mode = MeshBender.FillingMode.StretchToInterval;
        meshBender.SetInterval(spline, 0, 0.01f);
    }
}
